global:
  scrape_interval:
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s  #global catch time
    static_configs:
      - targets: ['192.168.2.248:9090']

  - job_name: 'social-api'
    static_configs:
      - targets: [ '192.168.2.248:4001' ]
        labels:
          job: social-api
          app: social-api
          env: dev
  - job_name: 'social-rpc'
    static_configs:
      - targets: [ '192.168.2.248:4002' ]
        labels:
          job: social-rpc
          app: social-rpc
          env: dev
  - job_name: 'video-api'
    static_configs:
      - targets: [ '192.168.2.248:4003' ]
        labels:
          job: video-api
          app: video-api
          env: dev
  - job_name: 'video-rpc'
    static_configs:
      - targets: [ '192.168.2.248:4004' ]
        labels:
          job: video-rpc
          app: video-rpc
          env: dev
  - job_name: 'user-api'
    static_configs:
      - targets: ['192.168.2.248:4005']
        labels:
          job: user-api
          app: user-api
          env: dev
  - job_name: 'user-rpc'
    static_configs:
      - targets: ['192.168.2.248:4006']
        labels:
          job: user-rpc
          app: user-rpc
          env: dev
  - job_name: 'mqueue'
    static_configs:
      - targets: [ '192.168.2.248:4007' ]
        labels:
          job: mqueue
          app: mqueue
          env: dev
  - job_name: 'search-api'
    static_configs:
      - targets: [ '192.168.2.248:4008' ]
        labels:
          job: search-api
          app: search-api
          env: dev
  - job_name: 'search-rpc'
    static_configs:
      - targets: [ '192.168.2.248:4009' ]
        labels:
          job: search-rpc
          app: search-rpc
          env: dev


