// Code generated by goctl. DO NOT EDIT.
package types

type Video struct {
	Id           int64  `json:"id"`
	OwnerId      int64  `json:"owner_id"`
	OwnerName    string `json:"owner_name"`
	SectionId    int64  `json:"section_id"`
	TagIds       string `json:"tag_ids"`
	Title        string `json:"title"`
	PlayUrl      string `json:"play_url"`
	CoverUrl     string `json:"cover_url"`
	CommentCount int64  `json:"comment_count"`
	LikeCount    int64  `json:"like_count"`
}

type VideoRecommendReq struct {
	SectionId int64 `json:"section_id" validate:"required"`
	Count     int64 `json:"count" validate:"required"`
}

type VideoRecommendResp struct {
	Videos []*Video `json:"videos"`
}
