// Code generated by goctl. DO NOT EDIT.
// Source: recommend.proto

package recommend

import (
	"context"

	"go-zero-douyin/apps/recommend/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	VideoRecommendSectionReq  = pb.VideoRecommendSectionReq
	VideoRecommendSectionResp = pb.VideoRecommendSectionResp

	Recommend interface {
		VideoRecommendSection(ctx context.Context, in *VideoRecommendSectionReq, opts ...grpc.CallOption) (*VideoRecommendSectionResp, error)
	}

	defaultRecommend struct {
		cli zrpc.Client
	}
)

func NewRecommend(cli zrpc.Client) Recommend {
	return &defaultRecommend{
		cli: cli,
	}
}

func (m *defaultRecommend) VideoRecommendSection(ctx context.Context, in *VideoRecommendSectionReq, opts ...grpc.CallOption) (*VideoRecommendSectionResp, error) {
	client := pb.NewRecommendClient(m.cli.Conn())
	return client.VideoRecommendSection(ctx, in, opts...)
}
