// Code generated by goctl. DO NOT EDIT.
package types

type PublishVideoReq struct {
	Title string `form:"title" validate:"required"`
}

type PublishVideoResp struct {
	Id       int64  `json:"id"`
	OwnerId  int64  `json:"owner_id"`
	VideoUrl string `json:"video_url"`
	CoverUrl string `json:"cover_url"`
}
