// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: rpc/pb/likerpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoLikeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId int64 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	UserId  int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *VideoLikeReq) Reset() {
	*x = VideoLikeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pb_likerpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoLikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoLikeReq) ProtoMessage() {}

func (x *VideoLikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pb_likerpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoLikeReq.ProtoReflect.Descriptor instead.
func (*VideoLikeReq) Descriptor() ([]byte, []int) {
	return file_rpc_pb_likerpc_proto_rawDescGZIP(), []int{0}
}

func (x *VideoLikeReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *VideoLikeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type VideoLikeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VideoLikeResp) Reset() {
	*x = VideoLikeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pb_likerpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoLikeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoLikeResp) ProtoMessage() {}

func (x *VideoLikeResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pb_likerpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoLikeResp.ProtoReflect.Descriptor instead.
func (*VideoLikeResp) Descriptor() ([]byte, []int) {
	return file_rpc_pb_likerpc_proto_rawDescGZIP(), []int{1}
}

type VideoUnlikeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId int64 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	UserId  int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *VideoUnlikeReq) Reset() {
	*x = VideoUnlikeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pb_likerpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoUnlikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoUnlikeReq) ProtoMessage() {}

func (x *VideoUnlikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pb_likerpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoUnlikeReq.ProtoReflect.Descriptor instead.
func (*VideoUnlikeReq) Descriptor() ([]byte, []int) {
	return file_rpc_pb_likerpc_proto_rawDescGZIP(), []int{2}
}

func (x *VideoUnlikeReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *VideoUnlikeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type VideoUnlikeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VideoUnlikeResp) Reset() {
	*x = VideoUnlikeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pb_likerpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoUnlikeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoUnlikeResp) ProtoMessage() {}

func (x *VideoUnlikeResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pb_likerpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoUnlikeResp.ProtoReflect.Descriptor instead.
func (*VideoUnlikeResp) Descriptor() ([]byte, []int) {
	return file_rpc_pb_likerpc_proto_rawDescGZIP(), []int{3}
}

type GetVideoLikeCountByVideoIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId int64 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
}

func (x *GetVideoLikeCountByVideoIdReq) Reset() {
	*x = GetVideoLikeCountByVideoIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pb_likerpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoLikeCountByVideoIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoLikeCountByVideoIdReq) ProtoMessage() {}

func (x *GetVideoLikeCountByVideoIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pb_likerpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoLikeCountByVideoIdReq.ProtoReflect.Descriptor instead.
func (*GetVideoLikeCountByVideoIdReq) Descriptor() ([]byte, []int) {
	return file_rpc_pb_likerpc_proto_rawDescGZIP(), []int{4}
}

func (x *GetVideoLikeCountByVideoIdReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type GetVideoLikeCountByVideoIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LikeCount int64 `protobuf:"varint,2,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
}

func (x *GetVideoLikeCountByVideoIdResp) Reset() {
	*x = GetVideoLikeCountByVideoIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pb_likerpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoLikeCountByVideoIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoLikeCountByVideoIdResp) ProtoMessage() {}

func (x *GetVideoLikeCountByVideoIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pb_likerpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoLikeCountByVideoIdResp.ProtoReflect.Descriptor instead.
func (*GetVideoLikeCountByVideoIdResp) Descriptor() ([]byte, []int) {
	return file_rpc_pb_likerpc_proto_rawDescGZIP(), []int{5}
}

func (x *GetVideoLikeCountByVideoIdResp) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type GetUserLikeVideoIdListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetUserLikeVideoIdListReq) Reset() {
	*x = GetUserLikeVideoIdListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pb_likerpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserLikeVideoIdListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLikeVideoIdListReq) ProtoMessage() {}

func (x *GetUserLikeVideoIdListReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pb_likerpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLikeVideoIdListReq.ProtoReflect.Descriptor instead.
func (*GetUserLikeVideoIdListReq) Descriptor() ([]byte, []int) {
	return file_rpc_pb_likerpc_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserLikeVideoIdListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserLikeVideoIdListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoIdList []int64 `protobuf:"varint,1,rep,packed,name=video_id_list,json=videoIdList,proto3" json:"video_id_list,omitempty"`
}

func (x *GetUserLikeVideoIdListResp) Reset() {
	*x = GetUserLikeVideoIdListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_pb_likerpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserLikeVideoIdListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLikeVideoIdListResp) ProtoMessage() {}

func (x *GetUserLikeVideoIdListResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pb_likerpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLikeVideoIdListResp.ProtoReflect.Descriptor instead.
func (*GetUserLikeVideoIdListResp) Descriptor() ([]byte, []int) {
	return file_rpc_pb_likerpc_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserLikeVideoIdListResp) GetVideoIdList() []int64 {
	if x != nil {
		return x.VideoIdList
	}
	return nil
}

var File_rpc_pb_likerpc_proto protoreflect.FileDescriptor

var file_rpc_pb_likerpc_proto_rawDesc = []byte{
	0x0a, 0x14, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x6c, 0x69, 0x6b, 0x65, 0x72, 0x70, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x42, 0x0a, 0x0c, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x0f,
	0x0a, 0x0d, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x44, 0x0a, 0x0e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x6e, 0x6c, 0x69, 0x6b, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x6e,
	0x6c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x3a, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x69, 0x6b, 0x65, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6c, 0x69, 0x6b, 0x65,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x34, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x4c, 0x69, 0x6b, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x1a, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x6b, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x0d, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x0b, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x32, 0xaf, 0x02,
	0x0a, 0x07, 0x6c, 0x69, 0x6b, 0x65, 0x72, 0x70, 0x63, 0x12, 0x30, 0x0a, 0x09, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x34, 0x0a, 0x0b, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x55, 0x6e, 0x6c, 0x69, 0x6b, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x6e, 0x6c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x11,
	0x2e, 0x70, 0x62, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x63, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4c, 0x69, 0x6b,
	0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x12,
	0x21, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4c, 0x69, 0x6b,
	0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x1a, 0x22, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x57, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x4c, 0x69, 0x6b, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x6b,
	0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x6b, 0x65,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_pb_likerpc_proto_rawDescOnce sync.Once
	file_rpc_pb_likerpc_proto_rawDescData = file_rpc_pb_likerpc_proto_rawDesc
)

func file_rpc_pb_likerpc_proto_rawDescGZIP() []byte {
	file_rpc_pb_likerpc_proto_rawDescOnce.Do(func() {
		file_rpc_pb_likerpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_pb_likerpc_proto_rawDescData)
	})
	return file_rpc_pb_likerpc_proto_rawDescData
}

var file_rpc_pb_likerpc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rpc_pb_likerpc_proto_goTypes = []interface{}{
	(*VideoLikeReq)(nil),                   // 0: pb.VideoLikeReq
	(*VideoLikeResp)(nil),                  // 1: pb.VideoLikeResp
	(*VideoUnlikeReq)(nil),                 // 2: pb.VideoUnlikeReq
	(*VideoUnlikeResp)(nil),                // 3: pb.VideoUnlikeResp
	(*GetVideoLikeCountByVideoIdReq)(nil),  // 4: pb.GetVideoLikeCountByVideoIdReq
	(*GetVideoLikeCountByVideoIdResp)(nil), // 5: pb.GetVideoLikeCountByVideoIdResp
	(*GetUserLikeVideoIdListReq)(nil),      // 6: pb.GetUserLikeVideoIdListReq
	(*GetUserLikeVideoIdListResp)(nil),     // 7: pb.GetUserLikeVideoIdListResp
}
var file_rpc_pb_likerpc_proto_depIdxs = []int32{
	0, // 0: pb.likerpc.VideoLike:input_type -> pb.VideoLikeReq
	2, // 1: pb.likerpc.VideoUnlike:input_type -> pb.VideoUnlikeReq
	4, // 2: pb.likerpc.GetVideoLikeCountByVideoId:input_type -> pb.GetVideoLikeCountByVideoIdReq
	6, // 3: pb.likerpc.GetUserLikeVideoIdList:input_type -> pb.GetUserLikeVideoIdListReq
	1, // 4: pb.likerpc.VideoLike:output_type -> pb.VideoLikeResp
	1, // 5: pb.likerpc.VideoUnlike:output_type -> pb.VideoLikeResp
	5, // 6: pb.likerpc.GetVideoLikeCountByVideoId:output_type -> pb.GetVideoLikeCountByVideoIdResp
	7, // 7: pb.likerpc.GetUserLikeVideoIdList:output_type -> pb.GetUserLikeVideoIdListResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_pb_likerpc_proto_init() }
func file_rpc_pb_likerpc_proto_init() {
	if File_rpc_pb_likerpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_pb_likerpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoLikeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_pb_likerpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoLikeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_pb_likerpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoUnlikeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_pb_likerpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoUnlikeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_pb_likerpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVideoLikeCountByVideoIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_pb_likerpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVideoLikeCountByVideoIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_pb_likerpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserLikeVideoIdListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_pb_likerpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserLikeVideoIdListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_pb_likerpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_pb_likerpc_proto_goTypes,
		DependencyIndexes: file_rpc_pb_likerpc_proto_depIdxs,
		MessageInfos:      file_rpc_pb_likerpc_proto_msgTypes,
	}.Build()
	File_rpc_pb_likerpc_proto = out.File
	file_rpc_pb_likerpc_proto_rawDesc = nil
	file_rpc_pb_likerpc_proto_goTypes = nil
	file_rpc_pb_likerpc_proto_depIdxs = nil
}
