// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package video

import (
	"context"

	"go-zero-douyin/apps/video/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteVideoReq    = pb.DeleteVideoReq
	DeleteVideoResp   = pb.DeleteVideoResp
	GetVideoByIdReq   = pb.GetVideoByIdReq
	GetVideoByIdResp  = pb.GetVideoByIdResp
	PublishVideoReq   = pb.PublishVideoReq
	PublishVideoResp  = pb.PublishVideoResp
	UserVideoListReq  = pb.UserVideoListReq
	UserVideoListResp = pb.UserVideoListResp
	VideoFeedReq      = pb.VideoFeedReq
	VideoFeedResp     = pb.VideoFeedResp
	VideoInfo         = pb.VideoInfo

	Video interface {
		// 视频相关功能
		PublishVideo(ctx context.Context, in *PublishVideoReq, opts ...grpc.CallOption) (*PublishVideoResp, error)
		VideoFeed(ctx context.Context, in *VideoFeedReq, opts ...grpc.CallOption) (*VideoFeedResp, error)
		UserVideoList(ctx context.Context, in *UserVideoListReq, opts ...grpc.CallOption) (*UserVideoListResp, error)
		DeleteVideo(ctx context.Context, in *DeleteVideoReq, opts ...grpc.CallOption) (*DeleteVideoResp, error)
		GetVideoById(ctx context.Context, in *GetVideoByIdReq, opts ...grpc.CallOption) (*GetVideoByIdResp, error)
	}

	defaultVideo struct {
		cli zrpc.Client
	}
)

func NewVideo(cli zrpc.Client) Video {
	return &defaultVideo{
		cli: cli,
	}
}

// 视频相关功能
func (m *defaultVideo) PublishVideo(ctx context.Context, in *PublishVideoReq, opts ...grpc.CallOption) (*PublishVideoResp, error) {
	client := pb.NewVideoClient(m.cli.Conn())
	return client.PublishVideo(ctx, in, opts...)
}

func (m *defaultVideo) VideoFeed(ctx context.Context, in *VideoFeedReq, opts ...grpc.CallOption) (*VideoFeedResp, error) {
	client := pb.NewVideoClient(m.cli.Conn())
	return client.VideoFeed(ctx, in, opts...)
}

func (m *defaultVideo) UserVideoList(ctx context.Context, in *UserVideoListReq, opts ...grpc.CallOption) (*UserVideoListResp, error) {
	client := pb.NewVideoClient(m.cli.Conn())
	return client.UserVideoList(ctx, in, opts...)
}

func (m *defaultVideo) DeleteVideo(ctx context.Context, in *DeleteVideoReq, opts ...grpc.CallOption) (*DeleteVideoResp, error) {
	client := pb.NewVideoClient(m.cli.Conn())
	return client.DeleteVideo(ctx, in, opts...)
}

func (m *defaultVideo) GetVideoById(ctx context.Context, in *GetVideoByIdReq, opts ...grpc.CallOption) (*GetVideoByIdResp, error) {
	client := pb.NewVideoClient(m.cli.Conn())
	return client.GetVideoById(ctx, in, opts...)
}
