// Code generated by goctl. DO NOT EDIT.
// Source: social.proto

package server

import (
	"context"

	"go-zero-douyin/apps/social/cmd/rpc/internal/logic"
	"go-zero-douyin/apps/social/cmd/rpc/internal/svc"
	"go-zero-douyin/apps/social/cmd/rpc/pb"
)

type SocialServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSocialServer
}

func NewSocialServer(svcCtx *svc.ServiceContext) *SocialServer {
	return &SocialServer{
		svcCtx: svcCtx,
	}
}

// 评论相关功能
func (s *SocialServer) AddComment(ctx context.Context, in *pb.AddCommentReq) (*pb.AddCommentResp, error) {
	l := logic.NewAddCommentLogic(ctx, s.svcCtx)
	return l.AddComment(in)
}

func (s *SocialServer) DelComment(ctx context.Context, in *pb.DelCommentReq) (*pb.DelCommentResp, error) {
	l := logic.NewDelCommentLogic(ctx, s.svcCtx)
	return l.DelComment(in)
}

func (s *SocialServer) GetVideoCommentListById(ctx context.Context, in *pb.GetCommentListByIdReq) (*pb.GetCommentListByIdResp, error) {
	l := logic.NewGetVideoCommentListByIdLogic(ctx, s.svcCtx)
	return l.GetVideoCommentListById(in)
}

func (s *SocialServer) GetCommentCountByVideoId(ctx context.Context, in *pb.GetCommentCountByVideoIdReq) (*pb.GetCommentCountByVideoIdResp, error) {
	l := logic.NewGetCommentCountByVideoIdLogic(ctx, s.svcCtx)
	return l.GetCommentCountByVideoId(in)
}

// 点赞相关功能
func (s *SocialServer) VideoLike(ctx context.Context, in *pb.VideoLikeReq) (*pb.VideoLikeResp, error) {
	l := logic.NewVideoLikeLogic(ctx, s.svcCtx)
	return l.VideoLike(in)
}

func (s *SocialServer) VideoUnlike(ctx context.Context, in *pb.VideoUnlikeReq) (*pb.VideoLikeResp, error) {
	l := logic.NewVideoUnlikeLogic(ctx, s.svcCtx)
	return l.VideoUnlike(in)
}

func (s *SocialServer) GetVideoLikeCountByVideoId(ctx context.Context, in *pb.GetVideoLikeCountByVideoIdReq) (*pb.GetVideoLikeCountByVideoIdResp, error) {
	l := logic.NewGetVideoLikeCountByVideoIdLogic(ctx, s.svcCtx)
	return l.GetVideoLikeCountByVideoId(in)
}

func (s *SocialServer) GetUserLikeVideoIdList(ctx context.Context, in *pb.GetUserLikeVideoIdListReq) (*pb.GetUserLikeVideoIdListResp, error) {
	l := logic.NewGetUserLikeVideoIdListLogic(ctx, s.svcCtx)
	return l.GetUserLikeVideoIdList(in)
}

// 关注功能
func (s *SocialServer) FollowUser(ctx context.Context, in *pb.FollowUserReq) (*pb.FollowUserResp, error) {
	l := logic.NewFollowUserLogic(ctx, s.svcCtx)
	return l.FollowUser(in)
}

func (s *SocialServer) UnfollowUser(ctx context.Context, in *pb.UnfollowUserReq) (*pb.UnfollowUserResp, error) {
	l := logic.NewUnfollowUserLogic(ctx, s.svcCtx)
	return l.UnfollowUser(in)
}
