// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	UserId   int64  `json:"userId"`
	Username string `json:"username"`
}

type RegisterReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required,password"`
}

type RegisterResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken int64  `json:"refresh_after"`
	ExpireTime   int64  `json:"expire_time"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_after"`
	ExpireTime   string `json:"expire_time"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserInfo User `json:"userInfo"`
}
