// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
}

type RegisterReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required,password"`
}

type RegisterResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken int64  `json:"refresh_after"`
	ExpireTime   int64  `json:"expire_time"`
}

type LoginReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type LoginResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken int64  `json:"refresh_after"`
	ExpireTime   int64  `json:"expire_time"`
}

type UserInfoReq struct {
	Id int64 `json:"id" validate:"required"`
}

type UserInfoResp struct {
	User User `json:"user"`
}

type UpdateUserReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required,password"`
}
