// Code generated by goctl. DO NOT EDIT.
package types

type VideoLikeReq struct {
	VideoId int64 `json:"video_id" validate:"required"`
}

type VideoUnlikeReq struct {
	VideoId int64 `json:"video_id" validate:"required"`
}

type GetUserLikeVideoIdListReq struct {
	UserId int64 `json:"user_id"`
}

type GetUserLikeVideoIdListResp struct {
	VideoIdList []int64 `json:"id_list"`
}
