// Code generated by MockGen. DO NOT EDIT.
// Source: ./rpc/internal/model/tagModel_gen.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	sql "database/sql"
	model "go-zero-douyin/apps/video/cmd/rpc/internal/model"
	reflect "reflect"

	squirrel "github.com/Masterminds/squirrel"
	gomock "github.com/golang/mock/gomock"
	sqlx "github.com/zeromicro/go-zero/core/stores/sqlx"
)

// MocktagModel is a mock of tagModel interface.
type MocktagModel struct {
	ctrl     *gomock.Controller
	recorder *MocktagModelMockRecorder
}

// MocktagModelMockRecorder is the mock recorder for MocktagModel.
type MocktagModelMockRecorder struct {
	mock *MocktagModel
}

// NewMocktagModel creates a new mock instance.
func NewMocktagModel(ctrl *gomock.Controller) *MocktagModel {
	mock := &MocktagModel{ctrl: ctrl}
	mock.recorder = &MocktagModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktagModel) EXPECT() *MocktagModelMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MocktagModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, session, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MocktagModelMockRecorder) Delete(ctx, session, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MocktagModel)(nil).Delete), ctx, session, id)
}

// DeleteSoft mocks base method.
func (m *MocktagModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *model.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSoft", ctx, session, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSoft indicates an expected call of DeleteSoft.
func (mr *MocktagModelMockRecorder) DeleteSoft(ctx, session, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSoft", reflect.TypeOf((*MocktagModel)(nil).DeleteSoft), ctx, session, data)
}

// FindAll mocks base method.
func (m *MocktagModel) FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, rowBuilder, orderBy)
	ret0, _ := ret[0].([]*model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MocktagModelMockRecorder) FindAll(ctx, rowBuilder, orderBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MocktagModel)(nil).FindAll), ctx, rowBuilder, orderBy)
}

// FindCount mocks base method.
func (m *MocktagModel) FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCount", ctx, countBuilder, field)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCount indicates an expected call of FindCount.
func (mr *MocktagModelMockRecorder) FindCount(ctx, countBuilder, field interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCount", reflect.TypeOf((*MocktagModel)(nil).FindCount), ctx, countBuilder, field)
}

// FindOne mocks base method.
func (m *MocktagModel) FindOne(ctx context.Context, id int64) (*model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, id)
	ret0, _ := ret[0].(*model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MocktagModelMockRecorder) FindOne(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MocktagModel)(nil).FindOne), ctx, id)
}

// FindOneByName mocks base method.
func (m *MocktagModel) FindOneByName(ctx context.Context, name string) (*model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByName", ctx, name)
	ret0, _ := ret[0].(*model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByName indicates an expected call of FindOneByName.
func (mr *MocktagModelMockRecorder) FindOneByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByName", reflect.TypeOf((*MocktagModel)(nil).FindOneByName), ctx, name)
}

// FindPageListByIdASC mocks base method.
func (m *MocktagModel) FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPageListByIdASC", ctx, rowBuilder, preMaxId, pageSize)
	ret0, _ := ret[0].([]*model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPageListByIdASC indicates an expected call of FindPageListByIdASC.
func (mr *MocktagModelMockRecorder) FindPageListByIdASC(ctx, rowBuilder, preMaxId, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPageListByIdASC", reflect.TypeOf((*MocktagModel)(nil).FindPageListByIdASC), ctx, rowBuilder, preMaxId, pageSize)
}

// FindPageListByIdDESC mocks base method.
func (m *MocktagModel) FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPageListByIdDESC", ctx, rowBuilder, preMinId, pageSize)
	ret0, _ := ret[0].([]*model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPageListByIdDESC indicates an expected call of FindPageListByIdDESC.
func (mr *MocktagModelMockRecorder) FindPageListByIdDESC(ctx, rowBuilder, preMinId, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPageListByIdDESC", reflect.TypeOf((*MocktagModel)(nil).FindPageListByIdDESC), ctx, rowBuilder, preMinId, pageSize)
}

// FindPageListByPage mocks base method.
func (m *MocktagModel) FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPageListByPage", ctx, rowBuilder, page, pageSize, orderBy)
	ret0, _ := ret[0].([]*model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPageListByPage indicates an expected call of FindPageListByPage.
func (mr *MocktagModelMockRecorder) FindPageListByPage(ctx, rowBuilder, page, pageSize, orderBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPageListByPage", reflect.TypeOf((*MocktagModel)(nil).FindPageListByPage), ctx, rowBuilder, page, pageSize, orderBy)
}

// FindPageListByPageWithTotal mocks base method.
func (m *MocktagModel) FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*model.Tag, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPageListByPageWithTotal", ctx, rowBuilder, page, pageSize, orderBy)
	ret0, _ := ret[0].([]*model.Tag)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindPageListByPageWithTotal indicates an expected call of FindPageListByPageWithTotal.
func (mr *MocktagModelMockRecorder) FindPageListByPageWithTotal(ctx, rowBuilder, page, pageSize, orderBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPageListByPageWithTotal", reflect.TypeOf((*MocktagModel)(nil).FindPageListByPageWithTotal), ctx, rowBuilder, page, pageSize, orderBy)
}

// FindSum mocks base method.
func (m *MocktagModel) FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSum", ctx, sumBuilder, field)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSum indicates an expected call of FindSum.
func (mr *MocktagModelMockRecorder) FindSum(ctx, sumBuilder, field interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSum", reflect.TypeOf((*MocktagModel)(nil).FindSum), ctx, sumBuilder, field)
}

// Insert mocks base method.
func (m *MocktagModel) Insert(ctx context.Context, session sqlx.Session, data *model.Tag) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, session, data)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MocktagModelMockRecorder) Insert(ctx, session, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MocktagModel)(nil).Insert), ctx, session, data)
}

// SelectBuilder mocks base method.
func (m *MocktagModel) SelectBuilder() squirrel.SelectBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectBuilder")
	ret0, _ := ret[0].(squirrel.SelectBuilder)
	return ret0
}

// SelectBuilder indicates an expected call of SelectBuilder.
func (mr *MocktagModelMockRecorder) SelectBuilder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectBuilder", reflect.TypeOf((*MocktagModel)(nil).SelectBuilder))
}

// Trans mocks base method.
func (m *MocktagModel) Trans(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trans", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Trans indicates an expected call of Trans.
func (mr *MocktagModelMockRecorder) Trans(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trans", reflect.TypeOf((*MocktagModel)(nil).Trans), ctx, fn)
}

// Update mocks base method.
func (m *MocktagModel) Update(ctx context.Context, session sqlx.Session, data *model.Tag) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, session, data)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MocktagModelMockRecorder) Update(ctx, session, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MocktagModel)(nil).Update), ctx, session, data)
}

// UpdateWithVersion mocks base method.
func (m *MocktagModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *model.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithVersion", ctx, session, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWithVersion indicates an expected call of UpdateWithVersion.
func (mr *MocktagModelMockRecorder) UpdateWithVersion(ctx, session, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithVersion", reflect.TypeOf((*MocktagModel)(nil).UpdateWithVersion), ctx, session, data)
}
