// Code generated by MockGen. DO NOT EDIT.
// Source: ./rpc/internal/model/videoModel_gen.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	sql "database/sql"
	model "go-zero-douyin/apps/video/cmd/rpc/internal/model"
	reflect "reflect"

	squirrel "github.com/Masterminds/squirrel"
	gomock "github.com/golang/mock/gomock"
	sqlx "github.com/zeromicro/go-zero/core/stores/sqlx"
)

// MockvideoModel is a mock of videoModel interface.
type MockvideoModel struct {
	ctrl     *gomock.Controller
	recorder *MockvideoModelMockRecorder
}

// MockvideoModelMockRecorder is the mock recorder for MockvideoModel.
type MockvideoModelMockRecorder struct {
	mock *MockvideoModel
}

// NewMockvideoModel creates a new mock instance.
func NewMockvideoModel(ctrl *gomock.Controller) *MockvideoModel {
	mock := &MockvideoModel{ctrl: ctrl}
	mock.recorder = &MockvideoModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvideoModel) EXPECT() *MockvideoModelMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockvideoModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, session, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockvideoModelMockRecorder) Delete(ctx, session, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockvideoModel)(nil).Delete), ctx, session, id)
}

// DeleteSoft mocks base method.
func (m *MockvideoModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *model.Video) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSoft", ctx, session, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSoft indicates an expected call of DeleteSoft.
func (mr *MockvideoModelMockRecorder) DeleteSoft(ctx, session, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSoft", reflect.TypeOf((*MockvideoModel)(nil).DeleteSoft), ctx, session, data)
}

// FindAll mocks base method.
func (m *MockvideoModel) FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*model.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, rowBuilder, orderBy)
	ret0, _ := ret[0].([]*model.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockvideoModelMockRecorder) FindAll(ctx, rowBuilder, orderBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockvideoModel)(nil).FindAll), ctx, rowBuilder, orderBy)
}

// FindCount mocks base method.
func (m *MockvideoModel) FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCount", ctx, countBuilder, field)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCount indicates an expected call of FindCount.
func (mr *MockvideoModelMockRecorder) FindCount(ctx, countBuilder, field interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCount", reflect.TypeOf((*MockvideoModel)(nil).FindCount), ctx, countBuilder, field)
}

// FindOne mocks base method.
func (m *MockvideoModel) FindOne(ctx context.Context, id int64) (*model.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, id)
	ret0, _ := ret[0].(*model.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockvideoModelMockRecorder) FindOne(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockvideoModel)(nil).FindOne), ctx, id)
}

// FindPageListByIdASC mocks base method.
func (m *MockvideoModel) FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*model.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPageListByIdASC", ctx, rowBuilder, preMaxId, pageSize)
	ret0, _ := ret[0].([]*model.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPageListByIdASC indicates an expected call of FindPageListByIdASC.
func (mr *MockvideoModelMockRecorder) FindPageListByIdASC(ctx, rowBuilder, preMaxId, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPageListByIdASC", reflect.TypeOf((*MockvideoModel)(nil).FindPageListByIdASC), ctx, rowBuilder, preMaxId, pageSize)
}

// FindPageListByIdDESC mocks base method.
func (m *MockvideoModel) FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*model.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPageListByIdDESC", ctx, rowBuilder, preMinId, pageSize)
	ret0, _ := ret[0].([]*model.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPageListByIdDESC indicates an expected call of FindPageListByIdDESC.
func (mr *MockvideoModelMockRecorder) FindPageListByIdDESC(ctx, rowBuilder, preMinId, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPageListByIdDESC", reflect.TypeOf((*MockvideoModel)(nil).FindPageListByIdDESC), ctx, rowBuilder, preMinId, pageSize)
}

// FindPageListByPage mocks base method.
func (m *MockvideoModel) FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*model.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPageListByPage", ctx, rowBuilder, page, pageSize, orderBy)
	ret0, _ := ret[0].([]*model.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPageListByPage indicates an expected call of FindPageListByPage.
func (mr *MockvideoModelMockRecorder) FindPageListByPage(ctx, rowBuilder, page, pageSize, orderBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPageListByPage", reflect.TypeOf((*MockvideoModel)(nil).FindPageListByPage), ctx, rowBuilder, page, pageSize, orderBy)
}

// FindPageListByPageWithTotal mocks base method.
func (m *MockvideoModel) FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*model.Video, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPageListByPageWithTotal", ctx, rowBuilder, page, pageSize, orderBy)
	ret0, _ := ret[0].([]*model.Video)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindPageListByPageWithTotal indicates an expected call of FindPageListByPageWithTotal.
func (mr *MockvideoModelMockRecorder) FindPageListByPageWithTotal(ctx, rowBuilder, page, pageSize, orderBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPageListByPageWithTotal", reflect.TypeOf((*MockvideoModel)(nil).FindPageListByPageWithTotal), ctx, rowBuilder, page, pageSize, orderBy)
}

// FindSum mocks base method.
func (m *MockvideoModel) FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSum", ctx, sumBuilder, field)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSum indicates an expected call of FindSum.
func (mr *MockvideoModelMockRecorder) FindSum(ctx, sumBuilder, field interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSum", reflect.TypeOf((*MockvideoModel)(nil).FindSum), ctx, sumBuilder, field)
}

// Insert mocks base method.
func (m *MockvideoModel) Insert(ctx context.Context, session sqlx.Session, data *model.Video) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, session, data)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockvideoModelMockRecorder) Insert(ctx, session, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockvideoModel)(nil).Insert), ctx, session, data)
}

// SelectBuilder mocks base method.
func (m *MockvideoModel) SelectBuilder() squirrel.SelectBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectBuilder")
	ret0, _ := ret[0].(squirrel.SelectBuilder)
	return ret0
}

// SelectBuilder indicates an expected call of SelectBuilder.
func (mr *MockvideoModelMockRecorder) SelectBuilder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectBuilder", reflect.TypeOf((*MockvideoModel)(nil).SelectBuilder))
}

// Trans mocks base method.
func (m *MockvideoModel) Trans(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trans", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Trans indicates an expected call of Trans.
func (mr *MockvideoModelMockRecorder) Trans(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trans", reflect.TypeOf((*MockvideoModel)(nil).Trans), ctx, fn)
}

// Update mocks base method.
func (m *MockvideoModel) Update(ctx context.Context, session sqlx.Session, data *model.Video) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, session, data)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockvideoModelMockRecorder) Update(ctx, session, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockvideoModel)(nil).Update), ctx, session, data)
}

// UpdateWithVersion mocks base method.
func (m *MockvideoModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *model.Video) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithVersion", ctx, session, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWithVersion indicates an expected call of UpdateWithVersion.
func (mr *MockvideoModelMockRecorder) UpdateWithVersion(ctx, session, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithVersion", reflect.TypeOf((*MockvideoModel)(nil).UpdateWithVersion), ctx, session, data)
}
