// Code generated by goctl. DO NOT EDIT.
// Source: likerpc.proto

package server

import (
	"context"

	"go-zero-douyin/apps/like/cmd/rpc/internal/logic"
	"go-zero-douyin/apps/like/cmd/rpc/internal/svc"
	"go-zero-douyin/apps/like/cmd/rpc/pb"
)

type LikerpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedLikerpcServer
}

func NewLikerpcServer(svcCtx *svc.ServiceContext) *LikerpcServer {
	return &LikerpcServer{
		svcCtx: svcCtx,
	}
}

func (s *LikerpcServer) VideoLike(ctx context.Context, in *pb.VideoLikeReq) (*pb.VideoLikeResp, error) {
	l := logic.NewVideoLikeLogic(ctx, s.svcCtx)
	return l.VideoLike(in)
}

func (s *LikerpcServer) VideoUnlike(ctx context.Context, in *pb.VideoUnlikeReq) (*pb.VideoLikeResp, error) {
	l := logic.NewVideoUnlikeLogic(ctx, s.svcCtx)
	return l.VideoUnlike(in)
}

func (s *LikerpcServer) GetVideoLikeCountByVideoId(ctx context.Context, in *pb.GetVideoLikeCountByVideoIdReq) (*pb.GetVideoLikeCountByVideoIdResp, error) {
	l := logic.NewGetVideoLikeCountByVideoIdLogic(ctx, s.svcCtx)
	return l.GetVideoLikeCountByVideoId(in)
}

func (s *LikerpcServer) GetUserLikeVideoIdList(ctx context.Context, in *pb.GetUserLikeVideoIdListReq) (*pb.GetUserLikeVideoIdListResp, error) {
	l := logic.NewGetUserLikeVideoIdListLogic(ctx, s.svcCtx)
	return l.GetUserLikeVideoIdList(in)
}
