// Code generated by goctl. DO NOT EDIT.
// Source: recommend.proto

package server

import (
	"context"

	"go-zero-douyin/apps/recommend/cmd/rpc/internal/logic"
	"go-zero-douyin/apps/recommend/cmd/rpc/internal/svc"
	"go-zero-douyin/apps/recommend/cmd/rpc/pb"
)

type RecommendServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRecommendServer
}

func NewRecommendServer(svcCtx *svc.ServiceContext) *RecommendServer {
	return &RecommendServer{
		svcCtx: svcCtx,
	}
}

func (s *RecommendServer) VideoRecommendSection(ctx context.Context, in *pb.VideoRecommendSectionReq) (*pb.VideoRecommendSectionResp, error) {
	l := logic.NewVideoRecommendSectionLogic(ctx, s.svcCtx)
	return l.VideoRecommendSection(in)
}
