// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:评论id" json:"id"`              // 评论id
	VideoID    int64          `gorm:"column:video_id;not null;comment:评论所属视频id" json:"video_id"`                   // 评论所属视频id
	UserID     int64          `gorm:"column:user_id;not null;comment:发表评论的用户id" json:"user_id"`                    // 发表评论的用户id
	Content    string         `gorm:"column:content;not null;comment:评论内容" json:"content"`                         // 评论内容
	CreateTime int64          `gorm:"column:create_time;type:int;type:unsigned;autoCreateTime" json:"create_time"` // 创建时间
	UpdateTime int64          `gorm:"column:update_time;type:int;type:unsigned;autoUpdateTime" json:"update_time"` // 更新时间
	DeleteTime gorm.DeletedAt `gorm:"column:delete_time;comment:删除时间" json:"delete_time"`                          // 删除时间
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
