// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameFollow = "follow"

// Follow mapped from table <follow>
type Follow struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:关注id" json:"id"`              // 关注id
	UserID     int64          `gorm:"column:user_id;not null;comment:被关注者id" json:"user_id"`                       // 被关注者id
	FollowerID int64          `gorm:"column:follower_id;not null;comment:关注者id" json:"follower_id"`                // 关注者id
	CreateTime int64          `gorm:"column:create_time;type:int;type:unsigned;autoCreateTime" json:"create_time"` // 创建时间
	UpdateTime int64          `gorm:"column:update_time;type:int;type:unsigned;autoUpdateTime" json:"update_time"` // 更新时间
	DeleteTime gorm.DeletedAt `gorm:"column:delete_time;comment:删除时间" json:"delete_time"`                          // 删除时间
}

// TableName Follow's table name
func (*Follow) TableName() string {
	return TableNameFollow
}
