// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"go-zero-douyin/common/xconst"
)

var (
	likeFieldNames          = builder.RawFieldNames(&Like{})
	likeRows                = strings.Join(likeFieldNames, ",")
	likeRowsExpectAutoSet   = strings.Join(stringx.Remove(likeFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	likeRowsWithPlaceHolder = strings.Join(stringx.Remove(likeFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheGoZeroDouyinLikeIdPrefix                    = "cache:goZeroDouyin:like:id:"
	cacheGoZeroDouyinLikeVideoIdUserIdIsDeletePrefix = "cache:goZeroDouyin:like:videoId:userId:isDelete:"
)

type (
	likeModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Like) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Like, error)
		FindOneByVideoIdUserIdIsDelete(ctx context.Context, videoId int64, userId int64, isDelete int64) (*Like, error)
		Update(ctx context.Context, session sqlx.Session, data *Like) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Like) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *Like) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*Like, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Like, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Like, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*Like, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*Like, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultLikeModel struct {
		sqlc.CachedConn
		table string
	}

	Like struct {
		Id         int64     `db:"id"`          // 点赞记录id
		VideoId    int64     `db:"video_id"`    // 视频id
		UserId     int64     `db:"user_id"`     // 用户id
		Status     int64     `db:"status"`      // 点赞状态：0取消点赞，1已点赞
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 更新时间
		DeleteTime time.Time `db:"delete_time"` // 删除时间
		IsDelete   int64     `db:"is_delete"`   // 是否被删除
		Version    int64     `db:"version"`     // 版本号
	}
)

func newLikeModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultLikeModel {
	return &defaultLikeModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`like`",
	}
}

func (m *defaultLikeModel) Insert(ctx context.Context, session sqlx.Session, data *Like) (sql.Result, error) {
	data.DeleteTime = time.Unix(0, 0)
	data.IsDelete = xconst.DelStateNo
	goZeroDouyinLikeIdKey := fmt.Sprintf("%s%v", cacheGoZeroDouyinLikeIdPrefix, data.Id)
	goZeroDouyinLikeVideoIdUserIdIsDeleteKey := fmt.Sprintf("%s%v:%v:%v", cacheGoZeroDouyinLikeVideoIdUserIdIsDeletePrefix, data.VideoId, data.UserId, data.IsDelete)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, likeRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.VideoId, data.UserId, data.Status, data.DeleteTime, data.IsDelete, data.Version)
		}
		return conn.ExecCtx(ctx, query, data.VideoId, data.UserId, data.Status, data.DeleteTime, data.IsDelete, data.Version)
	}, goZeroDouyinLikeIdKey, goZeroDouyinLikeVideoIdUserIdIsDeleteKey)
}

func (m *defaultLikeModel) FindOne(ctx context.Context, id int64) (*Like, error) {
	goZeroDouyinLikeIdKey := fmt.Sprintf("%s%v", cacheGoZeroDouyinLikeIdPrefix, id)
	var resp Like
	err := m.QueryRowCtx(ctx, &resp, goZeroDouyinLikeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and is_delete = ? limit 1", likeRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, xconst.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikeModel) FindOneByVideoIdUserIdIsDelete(ctx context.Context, videoId int64, userId int64, isDelete int64) (*Like, error) {
	goZeroDouyinLikeVideoIdUserIdIsDeleteKey := fmt.Sprintf("%s%v:%v:%v", cacheGoZeroDouyinLikeVideoIdUserIdIsDeletePrefix, videoId, userId, isDelete)
	var resp Like
	err := m.QueryRowIndexCtx(ctx, &resp, goZeroDouyinLikeVideoIdUserIdIsDeleteKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `video_id` = ? and `user_id` = ? and `is_delete` = ? and is_delete = ? limit 1", likeRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, videoId, userId, isDelete, xconst.DelStateNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikeModel) Update(ctx context.Context, session sqlx.Session, newData *Like) (sql.Result, error) {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return nil, err
	}
	goZeroDouyinLikeIdKey := fmt.Sprintf("%s%v", cacheGoZeroDouyinLikeIdPrefix, data.Id)
	goZeroDouyinLikeVideoIdUserIdIsDeleteKey := fmt.Sprintf("%s%v:%v:%v", cacheGoZeroDouyinLikeVideoIdUserIdIsDeletePrefix, data.VideoId, data.UserId, data.IsDelete)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, likeRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.VideoId, newData.UserId, newData.Status, newData.DeleteTime, newData.IsDelete, newData.Version, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.VideoId, newData.UserId, newData.Status, newData.DeleteTime, newData.IsDelete, newData.Version, newData.Id)
	}, goZeroDouyinLikeIdKey, goZeroDouyinLikeVideoIdUserIdIsDeleteKey)
}

func (m *defaultLikeModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, newData *Like) error {

	oldVersion := newData.Version
	newData.Version += 1

	var sqlResult sql.Result
	var err error

	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}
	goZeroDouyinLikeIdKey := fmt.Sprintf("%s%v", cacheGoZeroDouyinLikeIdPrefix, data.Id)
	goZeroDouyinLikeVideoIdUserIdIsDeleteKey := fmt.Sprintf("%s%v:%v:%v", cacheGoZeroDouyinLikeVideoIdUserIdIsDeletePrefix, data.VideoId, data.UserId, data.IsDelete)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, likeRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.VideoId, newData.UserId, newData.Status, newData.DeleteTime, newData.IsDelete, newData.Version, newData.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, newData.VideoId, newData.UserId, newData.Status, newData.DeleteTime, newData.IsDelete, newData.Version, newData.Id, oldVersion)
	}, goZeroDouyinLikeIdKey, goZeroDouyinLikeVideoIdUserIdIsDeleteKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultLikeModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *Like) error {
	data.IsDelete = data.Id
	data.DeleteTime = time.Now()
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "LikeModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultLikeModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("is_delete = ?", xconst.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultLikeModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("is_delete = ?", xconst.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultLikeModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*Like, error) {

	builder = builder.Columns(likeRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("is_delete = ?", xconst.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Like
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultLikeModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Like, error) {

	builder = builder.Columns(likeRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("is_delete = ?", xconst.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Like
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultLikeModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Like, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(likeRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("is_delete = ?", xconst.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*Like
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultLikeModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*Like, error) {

	builder = builder.Columns(likeRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("is_delete = ?", xconst.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Like
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultLikeModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*Like, error) {

	builder = builder.Columns(likeRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("is_delete = ?", xconst.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Like
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultLikeModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultLikeModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultLikeModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	goZeroDouyinLikeIdKey := fmt.Sprintf("%s%v", cacheGoZeroDouyinLikeIdPrefix, id)
	goZeroDouyinLikeVideoIdUserIdIsDeleteKey := fmt.Sprintf("%s%v:%v:%v", cacheGoZeroDouyinLikeVideoIdUserIdIsDeletePrefix, data.VideoId, data.UserId, data.IsDelete)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, goZeroDouyinLikeIdKey, goZeroDouyinLikeVideoIdUserIdIsDeleteKey)
	return err
}
func (m *defaultLikeModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheGoZeroDouyinLikeIdPrefix, primary)
}
func (m *defaultLikeModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and is_delete = ? limit 1", likeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, xconst.DelStateNo)
}

func (m *defaultLikeModel) tableName() string {
	return m.table
}
