// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	recommend "go-zero-douyin/apps/recommend/cmd/api/internal/handler/recommend"
	"go-zero-douyin/apps/recommend/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/video",
				Handler: recommend.VideoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/recommend/v1"),
	)
}
