apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-api
  namespace: go-zero-douyin
  labels:
    app: video-api
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: video-api
  template:
    metadata:
      labels:
        app: video-api
    spec:
      serviceAccountName: find-endpoints
      containers:
      - name: video-api
        image: 47.99.140.12:8077/go-zero-douyin/video-api:v1.0
        ports:
        - containerPort: 1003
        readinessProbe:
          tcpSocket:
            port: 1003
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 1003
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 200m
            memory: 50Mi
          limits:
            cpu: 300m
            memory: 1024Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      imagePullSecrets:
      - name: docker-login
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: video-api-svc
  namespace: go-zero-douyin
spec:
  ports:
  - nodePort: 31003
    port: 1003
    protocol: TCP
    targetPort: 1003
  type: NodePort
  selector:
    app: video-api

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: video-api-hpa-c
  namespace: go-zero-douyin
  labels:
    app: video-api-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: video-api-hpa-m
  namespace: go-zero-douyin
  labels:
    app: video-api-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
