// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameVideo = "video"

// Video mapped from table <video>
type Video struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title      string         `gorm:"column:title;not null" json:"title"`
	OwnerID    int64          `gorm:"column:owner_id;not null" json:"owner_id"`
	PlayURL    string         `gorm:"column:play_url;not null" json:"play_url"`
	CoverURL   string         `gorm:"column:cover_url;not null" json:"cover_url"`
	CreateTime int64          `gorm:"column:create_time;type:int;type:unsigned;autoCreateTime" json:"create_time"`
	UpdateTime int64          `gorm:"column:update_time;type:int;type:unsigned;autoUpdateTime" json:"update_time"`
	DeleteTime gorm.DeletedAt `gorm:"column:delete_time" json:"delete_time"`
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
